# Generated by Django 5.1.8 on 2025-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.CharField(default='n/a', max_length=20, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='seller',
            name='account',
            field=models.CharField(default='n/a', max_length=20, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='setupcompany',
            name='account',
            field=models.CharField(default='n/a', max_length=20, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst',
            field=models.CharField(default='n/a', max_length=15, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ifsc',
            field=models.CharField(default='n/a', max_length=15, verbose_name='IFSC code'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst',
            field=models.CharField(default='n/a', max_length=15, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='ifsc',
            field=models.CharField(default='n/a', max_length=15, verbose_name='IFSC code'),
        ),
        migrations.AlterField(
            model_name='setupcompany',
            name='gst',
            field=models.CharField(default='n/a', max_length=15, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='setupcompany',
            name='ifsc',
            field=models.CharField(default='n/a', max_length=15, verbose_name='IFSC code'),
        ),
    ]
